// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MetricsClient is an autogenerated mock type for the MetricsClient type
type MetricsClient struct {
	mock.Mock
}

// IncrementQueuePushCounter provides a mock function with given fields: submitted
func (_m *MetricsClient) IncrementQueuePushCounter(submitted string) {
	_m.Called(submitted)
}

// IncrementServerRequestCounter provides a mock function with given fields: status
func (_m *MetricsClient) IncrementServerRequestCounter(status string) {
	_m.Called(status)
}

// NewMetricsClient creates a new instance of MetricsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsClient {
	mock := &MetricsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
