// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	model "transcodeflow/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// JobTask is an autogenerated mock type for the JobTask type
type JobTask struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *JobTask) Execute(_a0 model.Job) (string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Job) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(model.Job) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(model.Job) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJobTask creates a new instance of JobTask. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobTask(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobTask {
	mock := &JobTask{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
